# gui:
#   authorColors:
#     "Rogin Farrer": "#ff0000"

git:
  pagers:
    - externalDiffCommand: difft --color=always

customCommands:
  - key: "G"
    command: "gh pr view -w {{.SelectedLocalBranch.Name}} || gh pr create -w {{.SelectedLocalBranch.Name}}"
    context: "localBranches"
    description: "Open Github PR in browser"
  - key: "G"
    command: "gh pr view -w {{.SelectedLocalBranch.Name}} || gh pr create -w {{.SelectedLocalBranch.Name}}"
    context: "commits"
    description: "Open Github PR in browser"
  - key: "<c-r>"
    command: "git pull --rebase origin main"
    context: "localBranches"
    description: "Pull rebase origin/main"
