"$schema" = 'https://starship.rs/config-schema.json'

# format = '$shell$all$character'

# format = """
# $shell\
# $hostname\
# $docker\
# $shlvl\
# $kubernetes\
# $directory\
# $git_branch\
# $git_commit\
# $git_state\
# $git_status\
# $hg_branch\
# $docker_context\
# $nodejs\
# $php\
# $python\
# $ruby\
# $rust\
# $swift\
# $nix_shell\
# $env_var\
# $line_break\
# $lua\
# $jobs\
# $status\
# $character"""

# [username]
# disabled = true

[cmd_duration]
disabled = true

[package]
disabled = true

[directory]
truncation_length = 2
fish_style_pwd_dir_length = 1

[git_branch]
# truncation_length = 20

[character]
vicmd_symbol = "[V](bold green) "

[sudo]
disabled = false

[shell]
disabled = false
fish_indicator = ''
zsh_indicator = 'zsh'

[gcloud]
disabled = true
