onboarding = false
[keys]
prefix = "ctrl+a"
# new_tab = 'cmd+t'

[[keys.command]]
key = "ctrl+h"
type = "plugin_action"
command = "smart-splits.nvim.left"
description = "navigate left (vim/herdr)"

[[keys.command]]
key = "ctrl+j"
type = "plugin_action"
command = "smart-splits.nvim.down"
description = "navigate down (vim/herdr)"

[[keys.command]]
key = "ctrl+k"
type = "plugin_action"
command = "smart-splits.nvim.up"
description = "navigate up (vim/herdr)"

[[keys.command]]
key = "ctrl+l"
type = "plugin_action"
command = "smart-splits.nvim.right"
description = "navigate right (vim/herdr)"

[[keys.command]]
key = "prefix+t"
type = "plugin_action"
command = "fullerzz.sesh.open-picker"
description = "sesh"

[ui.toast]
delivery = "herdr"

[ui]
show_agent_labels_on_pane_borders = true
prompt_new_tab_name = false
