#!/bin/bash

source "$XDG_CONFIG_HOME/sketchybar/notch.sh"
source "$XDG_CONFIG_HOME/sketchybar/colors.sh"
source "$XDG_CONFIG_HOME/sketchybar/icons.sh"

BAR_HEIGHT=32
BG_HEIGHT=$((BAR_HEIGHT - 4))
FONT="SF Pro"

PLUGIN_DIR="$XDG_CONFIG_HOME/sketchybar/plugins"
ITEM_DIR="$XDG_CONFIG_HOME/sketchybar/items"
export POPUP_CLICK_SCRIPT="sketchybar --set \$NAME popup.drawing=toggle"

bar=(
    height=$BAR_HEIGHT
    margin=-6
    corner_radius=10
    position=top
    color=$TRANSPARENT
    y_offset=2
)

sketchybar --bar "${bar[@]}"

defaults=(
    updates=when_shown
    icon.drawing=on
    icon.font="$FONT:Regular:16.0"
    icon.color=$ICON_COLOR
    label.font="$FONT:Regular:14.0"
    label.drawing=on
    label.color=$TEXT_COLOR
    popup.background.color=$BG_POPUP_COLOR
    popup.background.corner_radius=10
    popup.background.border_width=2
    popup.background.border_color=$BORDER_COLOR
    popup.blur_radius=100
)

sketchybar --default "${defaults[@]}"

# Right Side
# From right to left
source "$ITEM_DIR/time.sh"
source "$ITEM_DIR/date.sh"
source "$ITEM_DIR/fantastical.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"

# Middle
source "$ITEM_DIR/spotify.sh"

notch_spacer=(
    width=8
    script="$PLUGIN_DIR/notch_spacer.sh"
    drawing=!$HAS_NOTCH
)

sketchybar --add item notch_spacer q \
    --set notch_spacer "${notch_spacer[@]}" \
    --subscribe notch_spacer display_change system_woke

# Left Side
# From left to right
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

brackets=(
    background.color=$BG_LIGHT_COLOR
    background.height=$BG_HEIGHT
    background.corner_radius=8
    # background.border_color=$TRANSPARENT
    # background.border_width=3
)

SPOTIFY_LOC="center"
[ "$HAS_NOTCH" = "true" ] && SPOTIFY_LOC="q"

sketchybar --set spotify.anchor position=$SPOTIFY_LOC

# Right
sketchybar --add bracket status time date wifi battery volume_icon \
    --set status "${brackets[@]}"

# Center
sketchybar --add bracket music spotify.anchor \
    --set music "${brackets[@]}"

# Left
sketchybar --add bracket control apple "${spacesArray[@]}" \
    --set control "${brackets[@]}"

sketchybar --hotload on
sketchybar --update
